apiVersion: "scaffolder.backstage.io/v1beta3"
kind: "Template"
metadata:
  name: "dotnet-openapi-model-generator"
  title: "DotNet OpenAPI Model Generator"
  description: "Generates C# models for a given OpenAPI spec."
  tags:
    - "recommended"
    - "dotnet"
  annotations:
    github.com/project-slug: "/IntegrationWorks/dotnet-openapi-generator"
spec:
  owner: "user:guest"
  type: "service"
  parameters:
  - title: "Basic required information"
    required:
      - "name"
      - "description"
      - "owner"
    properties:
      name:
        title: "Name"
        type: "string"
        description: "The artifact name. eg (MyApp)"
        ui:field: "EntityNamePicker"
      description:
        title: "Description"
        type: "string"
        description: "Help others understand what this website is for."
      owner:
        title: "Owner"
        type: "string"
        description: "Owner of the component"
        ui:field: "OwnerPicker"
        ui:options:
          allowedKinds:
            - "Group"
  - title: "Repository info"
    requried:
      - "api-spec-repo"
      - "api-spec-path"
      - "target-repo"
      - "target-repo-token"
      - "target-models-path"
      - "target-cs-namespace"
    properties:
      api-spec-repo:
        title: "API Spec Repo"
        type: "string"
        description: "The repo which holds the API spec. eg (IntegrationWorks/OpenAPI-schema-specs)"
        ui:field: "RepoUrlPicker"
        ui:options: 
          requestUserCredentials:
            secretsKey: SPEC_OAUTH_TOKEN
            additionalScopes:
              github:
                - "workflow"
          allowedHosts:
            - "github.com"
      api-spec-path:
        title: "API Spec Path"
        type: "string"
        description: "The path to the API spec in the API spec repo. eg (YAML/petstore.yaml)"
      target-repo:
        title: "Target Git Repository"
        type: "string"
        description: "The repository of the repo which holds the DotNet application. eg (IntegrationWorks/DotNetDemo)"
        ui:field: "RepoUrlPicker"
        ui:options: 
          requestUserCredentials:
            secretsKey: TARGET_OAUTH_TOKEN
            additionalScopes:
              github:
                - "workflow"
          allowedHosts:
            - "github.com"
      target-models-path:
        title: "Target Models Path"
        type: "string"
        description: "The path which the generated code will be written to. eg (src/MyProject/Generated/Models)"
      target-cs-namespace:
        title: "Generated C# Namespace"
        type: "string"
        description: "The name of the namespace which will be used by the generator. eg (MyProject.Generated.Models)"
        ui:field: "EntityNamePicker"
  steps:
    - action: "github:actions:dispatch"
      name: "Run Generate Code GitHub Action"
      input:
        repoUrl: "github.com/IntegrationWorks/dotnet-openapi-generator"
        workflowId: "openapi-generate.yaml"
        branchOrTagName: "main"
        workflowInputs:
          api_spec_repo: "${{ parameters.api-spec-repo }}"
          api_spec_path: "${{ parameters.api-spec-path }}"
          target_repo: "${{ parameters.target-repo }}"
          target_path: "${{ parameters.target-models-path }}"
          namespace_name: "${{ parameters.target-cs-namespace }}"
