on: 
  workflow_dispatch:
    inputs:
      api_spec_repo:
        description: "API spec repository"
        required: true
      output_repo:
        description: "The output repository"
        required: true
      output_token:
        description: "A token with read/write permissions for the output repository"
        required: true
      output_path:
        description: "The path of the models folder"
        required: true
      namespace_name:
        description: "The the C# namespace to use for the models"
jobs:
  generate-models:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ github.event.inputs.api_spec_repo }}"
          path: "./spec"
      
      - name: "Checkout Repo"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ github.event.inputs.output_repo }}"
          path: "./app"
          token: "{{ github.event.inputs.output_token }}"
        
      - name: "Setup JDK 11"
        uses: "actions/setup-java@v1"
        with:
          java-version: 11

      - name: "Generate .NET Model Classes"
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.4.0/openapi-generator-cli-7.4.0.jar -O openapi-generator-cli.jar
          java -jar ./openapi-generator-cli.jar generate -i ./spec/petstore.json -g csharp -o ./out -p packageName=${{ github.event.inputs.namespace_name }}
          
          mkdir ./app/${{ github.event.inputs.output_path }}
          cp ./out/src/${{ github.event.inputs.namespace_name }}/Model/* ./app/${{ github.event.inputs.output_path }}
          cd ./app

          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Generate and add models."
          git push
